["protostar.config"]
protostar_version = "0.3.2"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
fibonacci = [
    "src/fibonacci.cairo",
]

revoked_reference = [
    "src/revoked_reference.cairo"
]

hints = [
    "src/hints.cairo"
]
const_and_references = [
    "src/const_and_references.cairo"
]
array_sum = [
    "src/array_felt.cairo"
]
field_element_felt = [
    "src/field_element_felt.cairo"
]
# puzzle = [
#     "src/puzzle.cairo"
# ]

voting = [
    "src/voting/voting.cairo"
]